### ISSUE TITLE
Cannot find protocol declaration for 'QueueNavigationActionDelegate'

### ISSUE THREAD

**Issue by ycc759** [queueit/react-native-queue-it#5]
### Version
`react-native-queue-it@1.1.1`

### Description

```
react-native-queue-it/ios/QueueIt.h:17:180: Cannot find protocol declaration for 'QueueNavigationActionDelegate'
react-native-queue-it/ios/QueueIt.m:46:17: Property 'queueNavigationActionDelegate' not found on object of type 'QueueITEngine *'
```

It makes compile failed on XCode and I tried to found 'QueueNavigationActionDelegate' on [ios-webui-sdk](https://github.com/queueit/ios-webui-sdk) and also not found. It should be a bug.

**Comment by sp0x** [comment]
QueueNavigationActionDelegate was removed since it's not supported anymore.

**Comment by sp0x** [comment]
The reference to `QueueNavigationActionDelegate` was removed in react-native-queue-it@1.1.2
