### ISSUE TITLE
Errors while building an Expo app: property 'queueitToken' not found on object of type '__strong id'

### ISSUE THREAD

**Issue by kvbalib** [queueit/react-native-queue-it#8]
Hello. I'm facing issues while trying to make the library work with an Expo app.

I've initiated fresh Expo app with dev-client and added react-native-queue-it as a dependency. Here's what's destroying the build:

<img width="986" alt="Zrzut ekranu 2022-03-3 o 10 39 32" src="https://user-images.githubusercontent.com/47784481/156538167-addaebad-2897-44c5-a4b4-c547becb0292.png">

Expo 44.0.6 (react-native 0.64.3) managed workflow, but I've tried to eject and had the same error
Xcode 13.2.1 Build version 13C100
Cocoapods 1.11.2
react-native-queue-it 1.1.6

**Comment by kvbalib** [comment]
I've just checked, and react-native-queue-it 1.1.5 works fine, the problem occurs when latest version is used. Will that make it impossible to update in the future?

**Comment by sp0x** [comment]
Can you try to update the dependencies? The underlying dependency for iOS was updated to version 3.0.10.
